# Generated by Django 6.0.3 on 2026-03-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_student_roll_number_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
