# Generated by Django 6.0.3 on 2026-03-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_student_degree_student_lecture_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lecture_subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
    ]
