# Generated by Django 6.0.3 on 2026-03-20 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='attendance.teacher'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='attendance.student'),
        ),
    ]
