# Generated by Django 6.0.3 on 2026-05-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_add_teacher_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
